# Generated by Django 4.2.8 on 2026-02-16 22:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('adjoint_admin', 'Adjoint Admin'), ('point_focal', 'Point Focal'), ('agent', 'Agent / Secrétariat'), ('vice_doyen', 'Vice-doyen'), ('student', 'Étudiant')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'core_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'core_department',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('period', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_focal', models.ForeignKey(blank=True, limit_choices_to={'role': 'point_focal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'core_note',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_solvable', models.BooleanField(default=False, help_text="L'étudiant a payé ses frais")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.department')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'db_table': 'core_student',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_number', models.CharField(max_length=50, unique=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Payé'), ('unpaid', 'Non payé'), ('partial', 'Partiellement payé')], default='unpaid', max_length=20)),
                ('visa_date', models.DateTimeField(blank=True, null=True)),
                ('printed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='core.note')),
                ('printed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_pvs', to=settings.AUTH_USER_MODEL)),
                ('visa_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'vice_doyen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visaed_pvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PV',
                'verbose_name_plural': 'PVs',
                'db_table': 'core_pv',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.student'),
        ),
        migrations.AddField(
            model_name='note',
            name='validated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'vice_doyen', 'agent']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('validate', 'Validation'), ('reject', 'Rejet'), ('import', 'Import'), ('export', 'Export'), ('login', 'Connexion')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('details_before', models.JSONField(blank=True, null=True)),
                ('details_after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['student', 'period'], name='core_note_student_f0c7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status'], name='core_note_status_4b8c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['point_focal'], name='core_note_point_f_7c3eeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('student', 'subject', 'period')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-created_at'], name='core_auditl_action__9792eb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'),
        ),
    ]
